import { sidebar } from "vuepress-theme-hope";

export default sidebar([
  "/intro",
  {
    text: "快速上手",
    icon: "creative",
    prefix: "/guide/",
    children: ["docker", "https", "init", "update", "nginx", "faq", "backup"],
  },
  {
    text: "功能",
    icon: "strong",
    prefix: "/feature/",
    children: [
      {
        text: "基本功能",
        icon: "launch",
        prefix: "basic/",
        children: [
          "article",
          "draft",
          "editor",
          "about",
          "setting",
          "comment",
          "pic",
          "overview",
          "category",
          "tag",
          "migrate",
        ],
      },
      {
        text: "进阶功能",
        icon: "advance",
        collapsible: true,
        prefix: "advance/",
        children: [
          "https",
          "rss",
          "customizing",
          "customPage",
          "collaborator",
          "backup",
          "log",
          "secure",
          "isr",
          "dark-mode",
          "links",
          "donate",
          "social",
          "search",
          "top",
          "seo",
          "hidden",
          "private",
          "customNav",
          "version",
          "visitor",
          "restore",
        ],
      },
    ],
  },
  {
    text: "参考",
    icon: "list",
    prefix: "/ref/",
    collapsible: true,
    children: "structure",
  },
]);
